// Reads public/sloboda_house_numbers.svg, extracts every <text id="..."> id,
// and emits src/houses.generated.ts as a frozen ID list.
//
// Run via `npm run generate-houses` (also fired by `prebuild`).
//
// We intentionally avoid an XML parser dependency — the SVG is small and the id
// attribute pattern is stable.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SVG_PATH = resolve(ROOT, "public", "sloboda_house_numbers.svg");
const OUT_PATH = resolve(ROOT, "src", "houses.generated.ts");

function extractIds(svg: string): string[] {
  const ids: string[] = [];
  const seen = new Set<string>();
  // Match <text ... id="_NN" ...> — id form is _<number> or _<number>_<number>
  const re = /<text\b[^>]*\bid="(_[0-9_]+)"/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(svg)) !== null) {
    const id = match[1];
    if (id && !seen.has(id)) {
      seen.add(id);
      ids.push(id);
    }
  }
  return ids;
}

function main(): void {
  const svg = readFileSync(SVG_PATH, "utf8");
  const ids = extractIds(svg);
  if (ids.length === 0) {
    throw new Error(`No <text id="..."> entries found in ${SVG_PATH}`);
  }

  const banner =
    "// AUTO-GENERATED by scripts/generate-houses.ts\n" +
    "// Do not edit by hand. Run `npm run generate-houses` to refresh.\n" +
    "// Source: public/sloboda_house_numbers.svg\n\n";

  const body =
    "export const HOUSE_IDS = [\n" +
    ids.map((id) => `  "${id}",`).join("\n") +
    "\n] as const;\n\n" +
    "export type HouseId = (typeof HOUSE_IDS)[number];\n";

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, banner + body, "utf8");
  // eslint-disable-next-line no-console
  process.stdout.write(`Wrote ${ids.length} house ids to ${OUT_PATH}\n`);
}

main();
